### ISSUE TITLE
I need more examples。

### ISSUE THREAD

**Issue by mrlmx** [haavardlian/escpos#1]
Hello, my English is not very good, The following text is translated by the translation software
, I hope it will not affect your reading.
Your project helped me a lot. But I don't know much about NodeJs, Can you write a few more examples? Such as pictures, QR Code, bar code, such as a simple example.
**Thanks very much!**

**Comment by haavardlian** [comment]
Hi i pasted some simple usage of bar code, qr, and image below.
For information about what the width, hight and error correct, etc. parameters mean you can look them up in some esc/pos manual like [this](http://www.aures-support.fr/DE/wp-content/uploads/2016/04/ESCPOS-command-manual20160428.pdf).

From my experience the impact of different parameters varies between printers.

If you are writing JavaScript without async/await support you will need to change it to use promise syntax.

```
const consoleAdapter = new Console();
const p = await new Printer(consoleAdapter).open();
const img = await Image.load("C:\temp\image.png");
await p.init()
     .barcode("7044610871172", Barcode.EAN13, 50, 2, Font.A, Position.Below)
     .qr("Hmm what kind of information should we store in these things?", QRErrorCorrecLevel.L, 4)
     .raster(img, RasterMode.Normal)
     .feed(4)
     .cut(true)
     .close();
```
