### ISSUE TITLE
Error module not found

### ISSUE THREAD

**Issue by iam-adty** [haavardlian/escpos#3]
i got these errors

> WARNING in ./~/bindings/bindings.js
> 76:22-40 Critical dependency: the request of a dependency is an expression
> 
> WARNING in ./~/bindings/bindings.js
> 76:43-53 Critical dependency: the request of a dependency is an expression
> 
> ERROR in ./~/escpos-print/adapters/Network.js
> Module not found: Error: Can't resolve 'net' in '/home/adty/Projects/klopos/web/myklopos/dev/node_modules/escpos-print/adapters'
>  @ ./~/escpos-print/adapters/Network.js 3:14-28
>  @ ./~/escpos-print/Adapters.js
>  @ ./src/js/pages/Report/Sales/BranchSales.js
>  @ ./src/js/config/routes.js
>  @ ./src/js/client.js
>  @ multi (webpack)-dev-server/client?http://192.168.1.19:8080 webpack/hot/dev-server ./js/client.js
> 
> ERROR in ./~/serialport/lib/serialport.js
> Module not found: Error: Can't resolve 'fs' in '/home/adty/Projects/klopos/web/myklopos/dev/node_modules/serialport/lib'
>  @ ./~/serialport/lib/serialport.js 16:9-22
>  @ ./~/escpos-print/adapters/Serial.js
>  @ ./~/escpos-print/Adapters.js
>  @ ./src/js/pages/Report/Sales/BranchSales.js
>  @ ./src/js/config/routes.js
>  @ ./src/js/client.js
>  @ multi (webpack)-dev-server/client?http://192.168.1.19:8080 webpack/hot/dev-server ./js/client.js
> 
> ERROR in ./~/serialport/lib/list-unix.js
> Module not found: Error: Can't resolve 'fs' in '/home/adty/Projects/klopos/web/myklopos/dev/node_modules/serialport/lib'
>  @ ./~/serialport/lib/list-unix.js 5:9-22
>  @ ./~/serialport/lib/bindings.js
>  @ ./~/serialport/lib/serialport.js
>  @ ./~/escpos-print/adapters/Serial.js
>  @ ./~/escpos-print/Adapters.js
>  @ ./src/js/pages/Report/Sales/BranchSales.js
>  @ ./src/js/config/routes.js
>  @ ./src/js/client.js
>  @ multi (webpack)-dev-server/client?http://192.168.1.19:8080 webpack/hot/dev-server ./js/client.js
> 
> ERROR in ./~/serialport/lib/list-unix.js
> Module not found: Error: Can't resolve 'child_process' in '/home/adty/Projects/klopos/web/myklopos/dev/node_modules/serialport/lib'
>  @ ./~/serialport/lib/list-unix.js 4:19-43
>  @ ./~/serialport/lib/bindings.js
>  @ ./~/serialport/lib/serialport.js
>  @ ./~/escpos-print/adapters/Serial.js
>  @ ./~/escpos-print/Adapters.js
>  @ ./src/js/pages/Report/Sales/BranchSales.js
>  @ ./src/js/config/routes.js
>  @ ./src/js/client.js
>  @ multi (webpack)-dev-server/client?http://192.168.1.19:8080 webpack/hot/dev-server ./js/client.js
> 
> ERROR in ./~/bindings/bindings.js
> Module not found: Error: Can't resolve 'fs' in '/home/adty/Projects/klopos/web/myklopos/dev/node_modules/bindings'
>  @ ./~/bindings/bindings.js 6:9-22
>  @ ./~/serialport/lib/bindings.js
>  @ ./~/serialport/lib/serialport.js
>  @ ./~/escpos-print/adapters/Serial.js
>  @ ./~/escpos-print/Adapters.js
>  @ ./src/js/pages/Report/Sales/BranchSales.js
>  @ ./src/js/config/routes.js
>  @ ./src/js/client.js
>  @ multi (webpack)-dev-server/client?http://192.168.1.19:8080 webpack/hot/dev-server ./js/client.js

what error are those and how to solve them? thanks.

**Comment by haavardlian** [comment]
Looks like webpack are not able to find fs, net or child_process which are all node standard node modules.
Which version of node are you running on?

**Comment by iam-adty** [comment]
Solved. The error appears when i run it on client's browser while the script run on server. browser can't find those node modules. Then i build the project as electron application. It runs without error.
