### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by ysfjwd** [haavardlian/escpos#4]
I was about to write the USB adapter for this but then i noticed the feature/next branch which has the USB adapter. When are you planning to release that on NPM?

//ysf

**Comment by ysfjwd** [comment]
also your node-usb dependency is hard linked to 1.3.0 tag on github, which is also the one on npm right now. what is the wisdom behind that?

**Comment by haavardlian** [comment]
I will probably release it pretty soon. I will look into it this weekend. The reason for the hard link is that the last time I was working on the usb stuff the 1.3.0 release was not on NPM.

**Comment by haavardlian** [comment]
@ysfjwd I'm looking at this now, and form what i can see  the 1.3.0 release of usb is still not available on NPM. I think I will wait with releasing a new version until i can fetch all packages from NPM.

**Comment by haavardlian** [comment]
2.0.0 is now released with USB 1.4.0
